// Categories structure for AI tools
const aiToolCategories = [
    'Machine Learning',
    'Natural Language Processing',
    'Computer Vision',
    'Robotics',
    'Expert Systems',
    'Fuzzy Logic',
    'Neural Networks',
    'Deep Learning',
    'Reinforcement Learning',
    'Data Mining',
    'Image Recognition',
    'Speech Recognition',
    'Predictive Analytics',
    'Chatbots',
    'Generative Adversarial Networks (GANs)',
    'Sentiment Analysis',
    'Time Series Analysis',
    'Recommendation Systems',
    'Automated Content Creation',
    'Fraud Detection',
    'Voice Assistants',
    'Anomaly Detection',
    'Supply Chain Optimization',
    'Predictive Maintenance',
    'Artificial Neural Networks',
    'Multi-Agent Systems',
    'Video Analysis',
    'Emotion AI',
    'Augmented Reality',
    'Virtual Reality',
    'Edge AI',
    'Federated Learning',
    'AI Ethics',
    'AI in Healthcare',
    'AI in Finance',
    'AI in Retail',
    'AI in Education',
    'AI in Agriculture',
    'AI in Manufacturing',
    'AI for Social Good',
    'Natural Language Understanding',
    'Real-time Data Processing',
    'Optical Character Recognition (OCR)',
    'Knowledge Graphs',
    'Semantic Analysis',
    'Data Visualization',
    'Graphical Models',
    'Online Learning',
    'Batch Learning',
    'Transfer Learning',
    'Automated Machine Learning (AutoML)',
    'AI for Cybersecurity',
    'Biosignal Processing',
    'AI for IoT',
    'Chatbot Development Frameworks',
    'Conversational AI',
    'AI for Customer Service',
    'Personalization Engines',
    'AI in Logistics',
    'AI for Smart Cities',
    'AI in Environmental Science',
    'Cognitive Computing',
    'Simulation-based Learning',
    'Contextual AI',
    'AI-powered Assistive Technologies',
    'Self-supervised Learning',
    'Game AI',
    'AI for Predictive Policing',
    'AI and Blockchain',
    'Intelligent Document Processing',
    'Hyperparameter Optimization',
    'Quality Control with AI',
    'AI for Wildlife Conservation',
    'Digital Twins',
    'Voice Recognition Systems',
    'AI for Journalism',
    'Neuro-symbolic AI',
    'Explainable AI (XAI)',
    'AI for Market Research',
    'Social Media Monitoring',
    'AI for Cryptocurrency Trading',
    'AI-driven Growth Hacking',
    'Personal Finance Management',
    'AI in Public Policy',
    'AI for Emergency Response',
    'Generative Design',
    'AI for Sports Analytics',
    'Intelligent Automation',
    'AI for Event Prediction',
    'Workflow Automation',
    'AI for Energy Management',
    'AI in Telecommunications',
    'Sustainable AI',
    'AI for Travel & Tourism',
    'Human-AI Collaboration',
    'AI for Drug Discovery',
    'Blockchain-based AI',
    'AI-driven Content Moderation',
    'Crisis Management with AI',
    'AI-enhanced User Experience',
    'AI for Talent Management',
    'AI in Supply Chain Management',
    'AI for Remote Sensing',
    'AI in Smart Homes',
    'AI for Language Translation',
    'AI for Financial Forecasting',
    'AI for Climate Change',
    'AI in Fashion Design',
    'AI for Health Monitoring',
    'AI in Construction',
    'AI for Real Estate Analysis',
    'AI for Heritage Preservation',
    'AI and Wearable Technology',
    'AI for Mental Health',
];

export default aiToolCategories;