export type Tool = {
  slug: string;
  name: string;
  tagline: string;
  description?: string;
  website: string;
  affiliateUrl?: string;
  pricing: "Free" | "Freemium" | "Paid";
  category: string;
  tags: string[];
  logoUrl?: string;
  featured?: boolean;
};

export const CATEGORIES = [
  "Writing & Content",
  "Image Generation",
  "Video & Audio",
  "Developer Tools",
  "Productivity",
  "Marketing",
  "Research & Education",
  "Customer Support",
  "Data & Analytics",
  "Design",
  "SEO",
  "Sales & CRM",
  "Finance",
  "HR & Recruitment",
  "Legal",
  "Healthcare",
  "Security",
  "Translation",
  "Social Media",
  "Gaming",
] as const;

export const tools: Tool[] = [
  // Writing & Content
  {
    slug: "chatgpt",
    name: "ChatGPT",
    tagline: "The world's most popular AI chatbot for writing, coding, and analysis.",
    description: "OpenAI's conversational AI that can write, code, analyze data, and answer questions.",
    website: "https://chat.openai.com",
    affiliateUrl: "https://chat.openai.com?ref=aiadvisor",
    pricing: "Freemium",
    category: "Writing & Content",
    tags: ["chatbot", "writing", "coding", "analysis"],
    featured: true,
  },
  {
    slug: "claude",
    name: "Claude",
    tagline: "Anthropic's AI assistant known for nuanced, thoughtful responses.",
    description: "Claude by Anthropic is a powerful AI assistant with a strong focus on safety and helpfulness.",
    website: "https://claude.ai",
    affiliateUrl: "https://claude.ai?ref=aiadvisor",
    pricing: "Freemium",
    category: "Writing & Content",
    tags: ["chatbot", "writing", "analysis", "safety"],
    featured: true,
  },
  {
    slug: "jasper",
    name: "Jasper",
    tagline: "AI writing assistant designed for marketing teams.",
    website: "https://jasper.ai",
    affiliateUrl: "https://jasper.ai?ref=aiadvisor",
    pricing: "Paid",
    category: "Writing & Content",
    tags: ["marketing", "copywriting", "content", "SEO"],
    featured: true,
  },
  {
    slug: "copy-ai",
    name: "Copy.ai",
    tagline: "Generate marketing copy, emails, and social posts instantly.",
    website: "https://copy.ai",
    affiliateUrl: "https://copy.ai?ref=aiadvisor",
    pricing: "Freemium",
    category: "Writing & Content",
    tags: ["copywriting", "marketing", "email"],
  },
  {
    slug: "writesonic",
    name: "Writesonic",
    tagline: "AI writing tool for blogs, ads, and product descriptions.",
    website: "https://writesonic.com",
    pricing: "Freemium",
    category: "Writing & Content",
    tags: ["blog", "ads", "product descriptions", "writing"],
  },
  {
    slug: "grammarly",
    name: "Grammarly",
    tagline: "AI-powered writing assistant for grammar, clarity, and tone.",
    website: "https://grammarly.com",
    pricing: "Freemium",
    category: "Writing & Content",
    tags: ["grammar", "editing", "proofreading", "writing"],
    featured: true,
  },
  {
    slug: "notion-ai",
    name: "Notion AI",
    tagline: "Built-in AI to help write, summarize, and brainstorm in Notion.",
    website: "https://notion.so/product/ai",
    pricing: "Paid",
    category: "Productivity",
    tags: ["notes", "productivity", "summarization", "writing"],
    featured: true,
  },
  {
    slug: "noted-ai",
    name: "Noted AI",
    tagline: "Turn meetings into summaries, tasks, and follow-ups.",
    website: "https://noted.ai",
    pricing: "Freemium",
    category: "Productivity",
    tags: ["meeting notes", "summarization", "productivity"],
  },
  {
    slug: "contentforge",
    name: "ContentForge",
    tagline: "Blog post + social media content in seconds.",
    website: "https://contentforge.ai",
    pricing: "Paid",
    category: "Writing & Content",
    tags: ["writing", "marketing", "content"],
  },
  // Image Generation
  {
    slug: "midjourney",
    name: "Midjourney",
    tagline: "Create stunning AI art and images via Discord.",
    description: "The most popular AI image generator for artists, designers, and creators.",
    website: "https://midjourney.com",
    affiliateUrl: "https://midjourney.com?ref=aiadvisor",
    pricing: "Paid",
    category: "Image Generation",
    tags: ["image", "art", "design", "creative"],
    featured: true,
  },
  {
    slug: "dall-e",
    name: "DALL-E 3",
    tagline: "OpenAI's image generation model for photorealistic visuals.",
    website: "https://openai.com/dall-e-3",
    pricing: "Paid",
    category: "Image Generation",
    tags: ["image", "art", "generation", "openai"],
    featured: true,
  },
  {
    slug: "stable-diffusion",
    name: "Stable Diffusion",
    tagline: "Open-source image generation model you can run locally.",
    website: "https://stability.ai",
    pricing: "Free",
    category: "Image Generation",
    tags: ["image", "open-source", "local", "art"],
    featured: true,
  },
  {
    slug: "adobe-firefly",
    name: "Adobe Firefly",
    tagline: "Generative AI built into Adobe's Creative Cloud.",
    website: "https://firefly.adobe.com",
    pricing: "Freemium",
    category: "Image Generation",
    tags: ["image", "design", "adobe", "creative"],
  },
  {
    slug: "pixelcraft",
    name: "PixelCraft",
    tagline: "Image generation + editing for marketing assets.",
    website: "https://pixelcraft.ai",
    pricing: "Paid",
    category: "Image Generation",
    tags: ["image", "design", "marketing"],
  },
  {
    slug: "canva-ai",
    name: "Canva AI",
    tagline: "AI-powered design tools built into Canva.",
    website: "https://canva.com/ai-image-generator",
    affiliateUrl: "https://canva.com?ref=aiadvisor",
    pricing: "Freemium",
    category: "Design",
    tags: ["design", "image", "templates", "branding"],
    featured: true,
  },
  // Video & Audio
  {
    slug: "runway",
    name: "Runway",
    tagline: "Professional AI video generation and editing tools.",
    description: "Create, edit, and transform video with powerful AI tools used by top creators.",
    website: "https://runwayml.com",
    affiliateUrl: "https://runwayml.com?ref=aiadvisor",
    pricing: "Freemium",
    category: "Video & Audio",
    tags: ["video", "generation", "editing", "creative"],
    featured: true,
  },
  {
    slug: "sora",
    name: "Sora",
    tagline: "OpenAI's text-to-video model for cinematic AI videos.",
    website: "https://openai.com/sora",
    pricing: "Paid",
    category: "Video & Audio",
    tags: ["video", "generation", "openai", "cinematic"],
    featured: true,
  },
  {
    slug: "elevenlabs",
    name: "ElevenLabs",
    tagline: "AI voice generation with ultra-realistic cloning and synthesis.",
    description: "The leading AI voice platform for creators, developers, and enterprises.",
    website: "https://elevenlabs.io",
    affiliateUrl: "https://elevenlabs.io?ref=aiadvisor",
    pricing: "Freemium",
    category: "Video & Audio",
    tags: ["voice", "audio", "text-to-speech", "cloning"],
    featured: true,
  },
  {
    slug: "descript",
    name: "Descript",
    tagline: "Edit audio and video by editing text.",
    website: "https://descript.com",
    pricing: "Freemium",
    category: "Video & Audio",
    tags: ["video", "audio", "podcast", "editing"],
  },
  {
    slug: "voicesmith",
    name: "VoiceSmith",
    tagline: "AI voice generator for podcasts and voiceovers.",
    website: "https://voicesmith.ai",
    pricing: "Freemium",
    category: "Video & Audio",
    tags: ["audio", "voice", "podcast"],
  },
  {
    slug: "clipgen",
    name: "ClipGen",
    tagline: "AI video repurposing for TikTok/Shorts/Reels.",
    website: "https://clipgen.ai",
    pricing: "Paid",
    category: "Video & Audio",
    tags: ["video", "creator", "repurpose"],
  },
  {
    slug: "heygen",
    name: "HeyGen",
    tagline: "Create AI avatar videos for marketing and training.",
    website: "https://heygen.com",
    affiliateUrl: "https://heygen.com?ref=aiadvisor",
    pricing: "Freemium",
    category: "Video & Audio",
    tags: ["video", "avatar", "marketing", "training"],
    featured: true,
  },
  // Developer Tools
  {
    slug: "github-copilot",
    name: "GitHub Copilot",
    tagline: "AI pair programmer that helps you write code faster.",
    description: "AI coding assistant integrated into VS Code and other editors.",
    website: "https://github.com/features/copilot",
    affiliateUrl: "https://github.com/features/copilot?ref=aiadvisor",
    pricing: "Paid",
    category: "Developer Tools",
    tags: ["coding", "developer", "autocomplete", "github"],
    featured: true,
  },
  {
    slug: "cursor",
    name: "Cursor",
    tagline: "AI-first code editor built on VS Code.",
    website: "https://cursor.sh",
    affiliateUrl: "https://cursor.sh?ref=aiadvisor",
    pricing: "Freemium",
    category: "Developer Tools",
    tags: ["coding", "editor", "developer", "AI"],
    featured: true,
  },
  {
    slug: "devpilot",
    name: "DevPilot",
    tagline: "Code assistant with repo-aware answers.",
    website: "https://devpilot.ai",
    pricing: "Freemium",
    category: "Developer Tools",
    tags: ["developer", "chat", "coding"],
  },
  {
    slug: "tabnine",
    name: "Tabnine",
    tagline: "AI code completion for all major languages and IDEs.",
    website: "https://tabnine.com",
    pricing: "Freemium",
    category: "Developer Tools",
    tags: ["coding", "autocomplete", "developer"],
  },
  {
    slug: "codeium",
    name: "Codeium",
    tagline: "Free AI code acceleration toolkit for developers.",
    website: "https://codeium.com",
    pricing: "Free",
    category: "Developer Tools",
    tags: ["coding", "free", "developer", "autocomplete"],
    featured: true,
  },
  // Marketing & SEO
  {
    slug: "surfer-seo",
    name: "Surfer SEO",
    tagline: "AI-powered SEO content optimization platform.",
    website: "https://surferseo.com",
    affiliateUrl: "https://surferseo.com?ref=aiadvisor",
    pricing: "Paid",
    category: "SEO",
    tags: ["SEO", "content", "ranking", "optimization"],
  },
  {
    slug: "semrush-ai",
    name: "SEMrush AI",
    tagline: "All-in-one marketing toolkit with AI capabilities.",
    website: "https://semrush.com",
    pricing: "Paid",
    category: "SEO",
    tags: ["SEO", "marketing", "keywords", "analytics"],
    featured: true,
  },
  {
    slug: "adcreative-ai",
    name: "AdCreative.ai",
    tagline: "Generate high-converting ad creatives in seconds.",
    website: "https://adcreative.ai",
    affiliateUrl: "https://adcreative.ai?ref=aiadvisor",
    pricing: "Paid",
    category: "Marketing",
    tags: ["ads", "marketing", "creative", "conversion"],
  },
  // Research & Education
  {
    slug: "perplexity",
    name: "Perplexity AI",
    tagline: "AI-powered search engine with cited answers.",
    description: "Real-time answers with sources, perfect for research and exploration.",
    website: "https://perplexity.ai",
    affiliateUrl: "https://perplexity.ai?ref=aiadvisor",
    pricing: "Freemium",
    category: "Research & Education",
    tags: ["search", "research", "citations", "answers"],
    featured: true,
  },
  {
    slug: "consensus",
    name: "Consensus",
    tagline: "AI search engine for scientific research papers.",
    website: "https://consensus.app",
    pricing: "Freemium",
    category: "Research & Education",
    tags: ["research", "academic", "science", "papers"],
  },
  {
    slug: "elicit",
    name: "Elicit",
    tagline: "AI research assistant for literature reviews.",
    website: "https://elicit.org",
    pricing: "Freemium",
    category: "Research & Education",
    tags: ["research", "academic", "literature", "review"],
  },
  // Customer Support
  {
    slug: "intercom-ai",
    name: "Intercom AI",
    tagline: "AI-powered customer support and engagement platform.",
    website: "https://intercom.com",
    pricing: "Paid",
    category: "Customer Support",
    tags: ["customer support", "chatbot", "CRM", "engagement"],
    featured: true,
  },
  {
    slug: "tidio",
    name: "Tidio",
    tagline: "Live chat and AI chatbots for customer service.",
    website: "https://tidio.com",
    affiliateUrl: "https://tidio.com?ref=aiadvisor",
    pricing: "Freemium",
    category: "Customer Support",
    tags: ["chatbot", "live chat", "customer support"],
  },
  // Data & Analytics
  {
    slug: "julius-ai",
    name: "Julius AI",
    tagline: "Chat with your data — analyze spreadsheets with AI.",
    website: "https://julius.ai",
    pricing: "Freemium",
    category: "Data & Analytics",
    tags: ["data", "analytics", "spreadsheet", "visualization"],
  },
  {
    slug: "obviously-ai",
    name: "Obviously AI",
    tagline: "No-code predictive analytics powered by AI.",
    website: "https://obviously.ai",
    pricing: "Paid",
    category: "Data & Analytics",
    tags: ["analytics", "prediction", "no-code", "data"],
  },
  // Social Media
  {
    slug: "buffer-ai",
    name: "Buffer AI",
    tagline: "AI-powered social media scheduling and content ideas.",
    website: "https://buffer.com",
    pricing: "Freemium",
    category: "Social Media",
    tags: ["social media", "scheduling", "content", "marketing"],
  },
  {
    slug: "predis-ai",
    name: "Predis.ai",
    tagline: "Create social media posts with AI in seconds.",
    website: "https://predis.ai",
    affiliateUrl: "https://predis.ai?ref=aiadvisor",
    pricing: "Freemium",
    category: "Social Media",
    tags: ["social media", "content", "design", "scheduling"],
  },
  // Translation
  {
    slug: "deepl",
    name: "DeepL",
    tagline: "The most accurate AI translation tool available.",
    website: "https://deepl.com",
    pricing: "Freemium",
    category: "Translation",
    tags: ["translation", "language", "localization"],
    featured: true,
  },
  // HR & Recruitment
  {
    slug: "paradox-ai",
    name: "Paradox AI",
    tagline: "AI recruiting assistant that automates hiring workflows.",
    website: "https://paradox.ai",
    pricing: "Paid",
    category: "HR & Recruitment",
    tags: ["HR", "recruiting", "hiring", "automation"],
  },
  // Finance
  {
    slug: "kensho",
    name: "Kensho",
    tagline: "AI analytics for financial data and markets.",
    website: "https://kensho.com",
    pricing: "Paid",
    category: "Finance",
    tags: ["finance", "analytics", "markets", "data"],
  },
  // Security
  {
    slug: "darktrace",
    name: "Darktrace",
    tagline: "AI cybersecurity platform for autonomous threat detection.",
    website: "https://darktrace.com",
    pricing: "Paid",
    category: "Security",
    tags: ["security", "cybersecurity", "threat detection", "AI"],
  },
  // Sales & CRM
  {
    slug: "gong-ai",
    name: "Gong.io",
    tagline: "Revenue intelligence platform powered by AI.",
    website: "https://gong.io",
    pricing: "Paid",
    category: "Sales & CRM",
    tags: ["sales", "CRM", "revenue", "analytics"],
    featured: true,
  },
  {
    slug: "salesforce-einstein",
    name: "Salesforce Einstein",
    tagline: "AI built into Salesforce CRM for smarter selling.",
    website: "https://salesforce.com/products/einstein",
    pricing: "Paid",
    category: "Sales & CRM",
    tags: ["sales", "CRM", "Salesforce", "automation"],
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: string): Tool[] {
  return tools.filter((t) => t.category === category);
}

export function getFeaturedTools(): Tool[] {
  return tools.filter((t) => t.featured);
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase().trim();
  if (!q) return tools;
  return tools.filter((t) =>
    [t.name, t.tagline, t.category, ...t.tags]
      .join(" ")
      .toLowerCase()
      .includes(q)
  );
}
